name: Bug Report
description: Create an issue to fix a bug/problem with the module.
labels:
  - bug
  - CHANGELOG.4.Fixed
assignees:
  - thedavecarroll
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using BluebirdPS and for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What is broken or not working?
      description: What behavior did you experience and what behavior did you expect?
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: PowerShell Environment
      description: |
        Please paste the results of `$PSVersionTable` here.
        Also, include the version of BluebirdPS. If running on v0.8.0 or later, you can run `Get-BluebirdPSVersion` and use that output.
        This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce-issue
    attributes:
      label: What steps will reproduce the behavior?
      description: In order to resolve the issue, we need to know how to reproduce it.
    validations:
      required: true
  - type: textarea
    id: console-output
    attributes:
      label: Relevant console output
      description: Please copy and paste any relevant console output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false