name: New Feature Request
description: Create an issue to request a new feature.
labels:
  - enhancement
  - CHANGELOG.6.Added
assignees:
  - thedavecarroll
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using BluebirdPS and for taking the time to submit your feature request!
  - type: textarea
    id: what-to-add
    attributes:
      label: What capability would you like to see added to BluebirdPS?
      description: Please use the Update a Command, Class, or Configuration Request if you want to change how a command works or the output of a command.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions or workarounds considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the new feature you are requesting.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false