name: Build Test for BluebirdPS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - BluebirdPS/**
      - build/**

defaults:
  run:
    shell: pwsh

jobs:
  test-all-platforms:
    name: Test all platforms/versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3

    # - name: Get Latest PSModuleCache Release
    #   uses: pozetroninc/github-action-get-latest-release@master
    #   id: psmodulecache
    #   with:
    #     owner: potatoqualitee
    #     repo: psmodulecache
    #     excludes: prerelease, draft

    - name: Install and cache psake, BuildHelpers and PowerShellBuild
      uses: potatoqualitee/psmodulecache@v5.1
      with:
        modules-to-cache: psake, BuildHelpers, PowerShellBuild

    - name: Build BluebirdPS
      run: |
        ./build.ps1
