name: Build Test for BluebirdPS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - BluebirdPS/**
      - build/**
      - psakeBuild.ps1
      - build.ps1

defaults:
  run:
    shell: pwsh

jobs:
  test-all-platforms:
    name: Test all platforms/versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install and cache required PowerShell modules
      uses: potatoqualitee/psmodulecache@v4.5
      with:
        modules-to-cache: psake, BuildHelpers, PowerShellBuild, PowerShellForGitHub

    - name: Build BluebirdPS
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
      run: |
        ./build.ps1
