name: Testing [System.Environment]::UserInteractive

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  test-all-platforms:
    name: Test if I can use [System.Environment]::UserInteractive to determine if it's running in a pipeline.
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Test Logging
      run: |
        ''
        '::group::Testing Logging'
        $PSVersionTable
        '::endgroup::'
        ''
    - name: Test [System.Environment]::UserInteractive
      run: |
        ''
        '::group::Testing Interactive Shell'
        [System.Environment]::UserInteractive ? 'Running interactively' : 'Running non-interactively'
        '::endgroup::'
        ''
